run: servidor.cpp Respuesta.o SocketDatagrama.o PaqueteDatagrama.o
	g++ Respuesta.cpp -c
	g++ SocketDatagrama.cpp -c
	g++ PaqueteDatagrama.cpp -c
	g++ servidor.cpp Respuesta.o SocketDatagrama.o PaqueteDatagrama.o -o server
